<!DOCTYPE html>

<html lang="en">

    <head>
        <meta charset="UTF-8" />
        <title><?=$this->escape($title)?></title>
        <link rel="stylesheet" type="text/css" media="screen" href="<?=$p?>/styles/<?=$style?>/screen.css" />
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    </head>

    <body class="wdb-faq-page">

        <div class="wdb-faq-content">

        <?=$content?>

        </div>

    </body>
</html>
