<?php

$this->setTitle('CSS');

?>

<h1>CSS</h1>

<ul>
<li><a href="http://www.css4you.de/">CSS 4 You</a></li>
<li><a href="http://de.selfhtml.org/navigation/css.htm">Kurzreferenz CSS</a></li>
<li><a href="http://www.andreas-kalt.de/webdesign/tutorials/float-theorie">Float—die Theorie</a></li>
</ul>

<p class="a">&#x2767;</p>


<h2>Das Reset-Stylesheet</h2>

<p class="a">&#x2767;</p>



<h2>Wichtige CSS-Techniken</h2>

<h3>Easy Clearing</h3>

<ul>
<li><a href="http://www.jassesnee.de/easyclear/">Einschließen von Floats ohne zusätzliches Markup</a>, <a href="http://perishablepress.com/press/2009/12/06/new-clearfix-hack/">The New Clearfix Method</a> (en)
</li>
</ul>

<h3>Faux Columns</h3>

<ul>
<li><a href="http://webdesign-passau.com/wordpress/faux-columns-technik/">Faux Columns Technik</a>, <a href="http://alistapart.byteshift.de/fauxcolumns/">Unechte Spalten</a></li>
</ul>

<h3>CSS Sprites</h3>

<ul>
<li><a href="http://bueltge.de/css-sprites-einfach-erklaert/675/">CSS Sprites einfach erklärt</a>, <a href="http://www.alistapart.com/articles/sprites">ALA: CSS Sprites</a> (en) </li>
</ul>

<h3>Sticky Footers</h3>

<ul>
<li><a href="http://ryanfait.com/resources/footer-stick-to-bottom-of-page/">Make the Footer Stick to the Bottom of a Page</a> (en), <a href="http://www.themaninblue.com/experiment/footerStickAlt/">footerStickAlt</a> (en)</li>
</ul>

<h3>Dropdown-Menü</h3>

<ul>
<li><a href="http://www.htmldog.com/articles/suckerfish/dropdowns/">Son of Suckerfish Dropdowns</a></li>
<li><a href="http://users.tpg.com.au/j_birch/plugins/superfish/">Superfish</a></li>
</ul>
