<?php

$this->setTitle('Design');

?>

<h1>Design</h1>



<h2 id="typographie">Typographie</h2>

<p class="a">&#x2767;</p>



<h2 id="ressourcen">Ressourcen</h2>

<ul>
<li><a href="http://www.oswd.org/">Open Source Web Design</a></li>
</ul>

<h3>Einführungen</h3>

<ul>
<li><a href="http://www.webdesign-tutorial.net/">Webdesign Tutorial</a></li>
</ul>

<ul>
<li>Schriftarten
<a href="http://www.codestyle.org/css/font-family/sampler-CombinedResults.shtml">Welche Schriftart ist wo verfügbar?</a> (en)</li>
</ul>
