<?php

$title = 'Home';

?>

<h1>Web-Entwicklung</h1>

<p class="c"><img src="./styles/fusia1.png" alt="Strichzeichnung einer Blüte" /></p>

<ol style="text-align: center; font-size: x-large;">
<li><a href="einleitung.html">Einleitung</a></li>
<li><a href="html.html">HTML</a></li>
<li><a href="css.html">CSS</a></li>
<li><a href="javascript.html">JavaScript</a></li>
<li><a href="php.html">PHP</a></li>
<li><a href="sql.html">SQL</a></li>
<li><a href="regex.html">Regex</a></li>
<li><a href="design.html">Design</a></li>
<li><a href="toolchain.html">Toolchain</a></li>
<li><a href="sonstiges.html">Sonstiges</a></li>
</ol>

<p class="a">&#x2767;</p>



<p>Dies ist eine Sammlung von Inhalten zum Thema Web-Entwicklung. Die Zusammenstellung folgt keinem bestimmten Plan, sondern wächst je nach Gelegenheit. Sie dient als zentraler Aufbewahrungsort für Texte, Fragmente, Links und Code-Snippets, die vor allem als Unterstützung für Einsteiger gedacht sind. Ein erklärtes Ziel ist, die Inhalte auf eine dezentrale und zugängliche Weise zu veröffentlichen, die nicht der Kontrolle einzelner Webseitenbetreiber unterliegt.</p>

