<?php

$this->setTitle('JavaScript');

?>

<h1>JavaScript</h1>

<ul>
<li><a href="https://developer.mozilla.org/en/JavaScript">Mozilla Developers Network</a>. Eine umfangreiche Referenz zum DOM-Scripting.</li>
<li><a href="http://eloquentjavascript.net/">Eloquent JavaScript</a>. Ein Einführungsbuch von Marijn Haverbeke.</li>
<li><a href="http://molily.de/js/">Einführung in JavaScript von molily</a></li>
</ul>

<p class="a">&#x2767;</p>



<h2 id="empfehlungen">Empfehlungen</h2>

<p class="a">&#x2767;</p>



<h2 id="ressourcen">Ressourcen</h2>

<ul>
<li><a href="http://www.howtocreate.co.uk/tutorials/javascript/">JavaScript tutorial</a> (en)</li>
</ul>

<h3>JS-Techniken</h3>

<ul>
<li>Ajax <a href="http://www.admin-wissen.de/tutorials/eigene-tutorials/webentwicklung/ajax-tutorial/">Eine Einführung in Ajax</a>, <a href="http://ajax.frozenfox.at/">5-teiliges Ajax-Tutorial</a></li>
<li>Diagramme erstellen <a href="http://elycharts.com/">Elycharts</a> (MIT-Lizenz, en)</li>
</ul>

