<?php

$title = 'JavaScript';

?>

<h1>JavaScript</h1>

<h2>Ressourcen</h2>

<h3>Nachschlagewerke</h3>

<ul>
<li><a href="https://developer.mozilla.org/en/JavaScript">Mozilla Developers Network</a> (en) Eine umfangreiche Referenz zum DOM-Scripting.</li>
</ul>

<h3>Einführungen</h3>

<ul>
<li><a href="http://www.howtocreate.co.uk/tutorials/javascript/">JavaScript tutorial</a> (en)</li>
</ul>

<h3>JS-Techniken</h3>

<ul>
<li>Ajax <a href="http://www.admin-wissen.de/tutorials/eigene-tutorials/webentwicklung/ajax-tutorial/">Eine Einführung in Ajax</a>, <a href="http://ajax.frozenfox.at/">5-teiliges Ajax-Tutorial</a></li>
<li>Diagramme erstellen <a href="http://elycharts.com/">Elycharts</a> (MIT-Lizenz, en)</li>
</ul>

