<?php

$this->setTitle('Toolchain');

?>

<h1>Toolchain</h1>



<h2 id="editor">Welcher Editor? WYSIWYG vs. WYSIWYM</h2>

<ul>
<li><a href="http://www.php.de/php-einsteiger/101627-editor-ide-let-me-tell-you-something.html">Vorstellung und Diskussion von Editoren auf php.de (August 2013)</a></li>
</ul>



<h2 id="scm">Versionsverwaltung</h2>


<ul>
<li><a href="http://semver.org/">Semantic Versioning</a></li>
<li><a href="http://gitlist.org/">GitList</a></li>
<li><a href="http://gitlabhq.com/">Gitlab</a></li>
<li><a href="http://www.php.de/software-design/94738-webdesigner-mit-git-vereinen.html">Webdesigner mit Git vereinen</a></li>
</ul>

